### ISSUE TITLE
Import annotations from genbank file

### ISSUE THREAD

**Issue by jwaldern** [Weeks-UNC/RNAvigate#36]
Instead of manually entering annotations and coordinates, it would be convenient to be able to pull annotations from an external file, such as a SnapGene file. Features and primers added to a sequence file in SnapGene can be exported as a standard GenBank text file, which can be parsed with the Bio.GenBank package of biopython (https://biopython.org/docs/1.75/api/Bio.GenBank.html).

Attached is an example of a standard genbank file, generated from an annotated SnapGene file. The goal would be to incorporate the primers (primer_bind) from this file as primer annotations in RNAvigate, and the misc_feature as spans (for example).

[INIP_3UTR_RC_direction_of_transcription_GB.txt](https://github.com/user-attachments/files/19454202/INIP_3UTR_RC_direction_of_transcription_GB.txt)

**Comment by Psirving** [comment]
Thanks Justin, this is a great idea. I've thought about this but not specifically for GenBank files. I'd also like to support .bed files for simple annotations. For both of these formats, the challenge is that, with RNAvigate's current structure, each type of annotation needs it's own keyword. It's not clear to me how to provide this type of file as a single keyword-argument to `rnav.Sample`.

I think this is a fairly high priority feature for when I get back to improving RNAvigate. Annotations are fairly annoying to input and people use them more than I thought they would.

If the problem is that you want to load the same annotations in many different notebooks or for different samples, there are a couple options. You can create the annotation in an external python file and import it to your notebook. Another option, which I might bake into RNAvigate, is to load the annotations from a yaml file which basically holds a dictionary. That can be done like this:

Create a file called `my_annotations.yaml`:

```yaml
AluJbp:
    spans: [[1930, 2132]]
    name: AluJb_p
    color: blue
    sequence: my_sequence.fa
AluJrm:
    spans: [[2674, 2981]]
    name: AluJr_m
    color: red
    sequence: my_sequence.fa
primer1:
    primers: [[209, 230], [3270, 3250]]
    name: primer1
    color: purple
    sequence: my_sequence.fa
```

Then in the notebook:

```python
import rnavigate as rnav
import yaml

with open("my_annotations.yaml", 'r') as file:
    anno = yaml.load(file)

print(anno) # make sure the order is preserved, I think it should be for python >3.9.

my_sample = rnav.Sample(
    sample="test",
    AluJbp=anno["AluJbp"],
    AluJrm=anno["AluJrm"],
    primer1=anno["primer1"]
)
```
